# SciKit Learn Preprocessing Overview

In [1]:
import numpy as np

In [2]:
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[60, 46],
       [ 8, 83],
       [20, 49],
       [96, 69],
       [23, 83],
       [67, 87],
       [37, 80],
       [29,  5],
       [87, 39],
       [80, 30]])

In [5]:
scaler_model = MinMaxScaler()

In [6]:
scaler_model.fit(data)

MinMaxScaler()

In [7]:
scaler_model.transform(data)

array([[0.59090909, 0.5       ],
       [0.        , 0.95121951],
       [0.13636364, 0.53658537],
       [1.        , 0.7804878 ],
       [0.17045455, 0.95121951],
       [0.67045455, 1.        ],
       [0.32954545, 0.91463415],
       [0.23863636, 0.        ],
       [0.89772727, 0.41463415],
       [0.81818182, 0.30487805]])

In [8]:
# In one step
result = scaler_model.fit_transform(data)

In [9]:
result

array([[0.59090909, 0.5       ],
       [0.        , 0.95121951],
       [0.13636364, 0.53658537],
       [1.        , 0.7804878 ],
       [0.17045455, 0.95121951],
       [0.67045455, 1.        ],
       [0.32954545, 0.91463415],
       [0.23863636, 0.        ],
       [0.89772727, 0.41463415],
       [0.81818182, 0.30487805]])

In [10]:
import pandas as pd

In [11]:
data = pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [12]:
data.head()

f1  f2  f3  label
0  21  10  58     49
1  37  61  21     69
2  41   6   8     58
3  19  25  72      3
4  59  25  63     33

In [13]:
x = data[['f1','f2','f3']] # Alternatively x = data.drop('label',axis=1)
y = data['label']

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=101)

In [16]:
X_train.shape

(35, 3)

In [17]:
X_test.shape

(15, 3)

In [18]:
y_train.shape

(35,)

In [19]:
y_test.shape

(15,)

## Great Job!